version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: college
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  auth_service:
    build: ./auth
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:qwerty@db:5432/college"
      JWT_PRIVATE_KEY_FILE: /tmp/signature.pem
      JWT_PUBLIC_KEY_FILE: /tmp/signature.pub
    command: sh -c "python database.py && flask run --host=0.0.0.0 --port=8090"

  course_service:
    build: ./course
    ports:
      - "8091:8091"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:qwerty@db:5432/college"
      JWT_PUBLIC_KEY_FILE: /tmp/signature.pub
    command: sh -c "python database.py && flask run --host=0.0.0.0 --port=8091"

volumes:
  postgres_data: