version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: college
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth:
    build: .
    ports:
      - "8090:8090"
    environment:
      DATABASE_URL: "postgresql://postgres:qwerty@db:5432/college"
      JWT_PRIVATE_KEY_FILE: /app/configs/signature.pem
      JWT_PUBLIC_KEY_FILE: /app/configs/signature.pub
    volumes:
      - ./configs:/app/configs
    command: sh -c "python -c 'from database.session import init_db; init_db()' && python -m auth.app"

  course:
    build: .
    ports:
      - "8091:8091"
    environment:
      DATABASE_URL: "postgresql://postgres:qwerty@db:5432/college"
      JWT_PUBLIC_KEY_FILE: /app/configs/signature.pub
    volumes:
      - ./configs:/app/configs
    command: python -m course.app

volumes:
  postgres_data:
